# Generated by Django 3.2.3 on 2021-05-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0002_rename_network_switch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vlan',
            old_name='network',
            new_name='switch',
        ),
    ]
