# Generated by Django 3.2.3 on 2021-05-24 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0003_rename_network_vlan_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='switch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='networks.switch'),
        ),
    ]
